In [36]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.pipeline import make_pipeline
from sklearn.datasets import load_iris
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score

In [37]:
iris = load_iris()

In [42]:

l_scores=cross_val_score(LogisticRegression(C=0.5, max_iter = 100),iris.data,iris.target,cv=3)
l_scores

C:\Users\midhu\anaconda3\Lib\site-packages\sklearn\linear_model\_logistic.py:460: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


array([0.96, 0.94, 0.98])

In [43]:
d_scores=cross_val_score(DecisionTreeClassifier(), iris.data, iris.target,cv=3)
d_scores

array([0.98, 0.94, 1.  ])

In [44]:
np.average(d_scores)

0.9733333333333333

In [46]:
s_scores = cross_val_score(SVC(), iris.data, iris.target,cv=3)
s_scores

array([0.96, 0.98, 0.94])

In [49]:
r_scores = cross_val_score(RandomForestClassifier(n_estimators=40),iris.data,iris.target,cv=3)
r_scores

array([0.98, 0.92, 0.98])

In [50]:
np.average(s_scores)

0.96

In [51]:
np.average(r_scores)

0.96

In [53]:
np.average(l_scores)

0.96

## Better is DecisionTreeClassifier